spring.application.name=sbecom

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

project.images.path = images/;

spring.jpa.show-sql= true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret.key=${JWT_SECRET_KEY}
jwt.key.expiration.time=300000
jwt.cookie=springBootEcomJWTCookie

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG
